import Head from "next/head";
import Image from "next/image";
import TechButton from "../src/components/reusableComponents/TechButton";
import styles from "../styles/Home.module.css";
import { FaDatabase } from "react-icons/fa";
import { FaClipboardList } from "react-icons/fa";
import { AiFillFolderAdd } from "react-icons/ai";
import { BsFillCalculatorFill } from "react-icons/bs";
import { FaUserAlt } from "react-icons/fa";
import LayoutComponent from "../src/components/reusableComponents/LayoutComponent";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LayoutComponent>
        <>
          <h1 className={styles.header}>POSTARKIV</h1>
          <TechButton
            icon={<FaDatabase style={{ marginRight: "1rem" }} />}
            title="Søk i postarkiv"
            link="/search"
          />
          <TechButton
            icon={<FaClipboardList style={{ marginRight: "1rem" }} />}
            title="Skurliste"
          />
          <TechButton
            icon={<AiFillFolderAdd style={{ marginRight: "1rem" }} />}
            title="Ny post"
          />
          <TechButton
            icon={<BsFillCalculatorFill style={{ marginRight: "1rem" }} />}
            title="Kalkulator"
          />
          <TechButton
            icon={<FaUserAlt style={{ marginRight: "1rem" }} />}
            title="Login"
          />
        </>
      </LayoutComponent>
    </div>
  );
}
