import Head from "next/head";
import Image from "next/image";
import TechButton from "../src/components/reusableComponents/TechButton";
import styles from "../styles/Home.module.css";
import { FaDatabase } from "react-icons/fa";
import { FaClipboardList } from "react-icons/fa";
import { AiFillFolderAdd } from "react-icons/ai";
import { BsFillCalculatorFill } from "react-icons/bs";
import { FaUserAlt } from "react-icons/fa";
import { BiSearchAlt } from "react-icons/bi";
import LayoutComponent from "../src/components/reusableComponents/LayoutComponent";

interface PosterProps {
  poster: {
    length: {
      startRings: [
        {
          input: {
            type: number;
          };
        }
      ];
      rawInput: [
        {
          input: {
            type: number;
          };
          ring: {
            type: number;
          };
          shims: {
            type: number;
          };
          shims2: {
            type: number;
          };
          shims3: {
            type: number;
          };
        }
      ];
      endRings: [
        {
          input: {
            type: number;
          };
        }
      ];
      blades: {
        bladStamme: {
          type: number;
        };
      };
      header: {
        type: string;
      };
      prosent: {
        type: string;
      };
      planker: {
        type: string;
      };
      spes: {
        type: string;
      };
      nameClass: {
        type: string;
      };
      date: {
        type: Date;
      };
      editDate: {
        type: Date;
      };
    };
    startRings: [
      {
        input: {
          type: number;
        };
      }
    ];
    rawInput: [
      {
        input: {
          type: number;
        };
        ring: {
          type: number;
        };
        shims: {
          type: number;
        };
        shims2: {
          type: number;
        };
        shims3: {
          type: number;
        };
      }
    ];
    endRings: [
      {
        input: {
          type: number;
        };
      }
    ];
    blades: {
      bladStamme: {
        type: number;
      };
    };
    header: {
      type: string;
    };
    prosent: {
      type: string;
    };
    planker: {
      type: string;
    };
    spes: {
      type: string;
    };
    nameClass: {
      type: string;
    };
    date: {
      type: Date;
    };
    editDate: {
      type: Date;
    };
  };
  skurliste: {
    length: {};
  };
}
[];

export default function Home({ poster, skurliste }: PosterProps) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Postarkiv</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LayoutComponent>
        <>
          <h1 className={styles.header}>POSTARKIV</h1>
          <TechButton
            icon={<BiSearchAlt style={{ marginRight: "1rem" }} />}
            title="Søk i postarkiv"
            link="/search"
            info={`(${poster && poster.length})`}
          />
          <TechButton
            icon={<FaClipboardList style={{ marginRight: "1rem" }} />}
            title="Skurliste"
            link="/skurliste"
            info={`(${skurliste && skurliste.length})`}
          />
          <TechButton
            icon={<FaDatabase style={{ marginRight: "1rem" }} />}
            title="Lag ny post"
          />
          <TechButton
            icon={<BsFillCalculatorFill style={{ marginRight: "1rem" }} />}
            title="Kalkulator"
          />
          <TechButton
            icon={<FaUserAlt style={{ marginRight: "1rem" }} />}
            title="Login"
          />
        </>
      </LayoutComponent>
    </div>
  );
}
